### PR TITLE
run all openshift4 tests even if one fails

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
Blocked by this issue: https://github.com/sclorg/container-common-scripts/pull/233

**Review by phracek — APPROVED** [review]
LGTM. Thanks for the PR!

Let's see on the test result

**Comment by phracek** [comment]
[test-all]

**Comment by zmiklank** [comment]
Testing Farm - RHEL7 - OpenShift 4 tests failed on scp transfer error.

**Pull request merged**
