### PR TITLE
Add centos 8 dockerfile

### PR DESCRIPTION
**Pull request by hhorak**

### CODE REVIEW

**Comment by hhorak** [comment]
Already added in https://github.com/sclorg/httpd-container/pull/98.

**Comment by hhorak** [comment]
> Already added in #98.

My mistake, only imagestream was added, not a Dockerfile. Re-opening.

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
It is not clear whether we need centos8 images at all if we have ubi images. I think we can close this until we know for sure we need it.

**Comment by phracek** [comment]
Closing it. We do not need it.

**Comment by phracek** [comment]
This pull rquest is closed in favor https://github.com/sclorg/httpd-container/pull/143

**Pull request closed without merging**
