### PR TITLE
Update common.sh

### PR DESCRIPTION
**Pull request by yohanesws**
Make it right ssl.conf by adding port change for VirtualHost Default also.

Before it fix:

sh-4.2$ curl -kv https://localhost:8443                                                                                                                                
* About to connect() to localhost port 8443 (#0)                                                                                                                       
*   Trying ::1...                                                                                                                                                      
* Connection refused                                                                                                                                                   
*   Trying 127.0.0.1...                                                                                                                                                
* Connected to localhost (127.0.0.1) port 8443 (#0)                                                                                                                    
* Initializing NSS with certpath: sql:/etc/pki/nssdb                                                                                                                   
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)                                                                                                                      
* SSL received a record that exceeded the maximum permissible length.                                                                                                  
* Closing connection 0                                                                                                                                                 
curl: (35) SSL received a record that exceeded the maximum permissible length.   

After it fix:
sh-4.2$ curl -kv https://localhost:8443                                                                                                                                
* About to connect() to localhost port 8443 (#0)                                                                                                                       
*   Trying ::1...                                                                                                                                                      
* Connection refused                                                                                                                                                   
*   Trying 127.0.0.1...                                                                                                                                                
* Connected to localhost (127.0.0.1) port 8443 (#0)                                                                                                                    
* Initializing NSS with certpath: sql:/etc/pki/nssdb                                                                                                                   
* skipping SSL peer certificate verification                                                                                                                           
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384                                                                                                           
* Server certificate:                                                                                                                                                  
*       subject: CN=*,OU=* Foundation,O=*,L=*,ST=*,C=*                                                                                                    
*       start date: May 31 09:00:37 2017 GMT                                                                                                                           
*       expire date: May 29 09:00:37 2027 GMT                                                                                                                          
*       common name: *                                                                                                                                          
*       issuer: CN=*,OU=RDC Foundation,O=*,L=*,ST=*,C=*                                                                                                     
> GET / HTTP/1.1                                                                                                                                                       
> User-Agent: curl/7.29.0                                                                                                                                              
> Host: localhost:8443                                                                                                                                                 
> Accept: */*                                                                                                                                                          
>                                                                                                                                                                      
< HTTP/1.1 200 OK

### CODE REVIEW

**Comment by omron93** [comment]
[test]

**Comment by hhorak** [comment]
@uhliarik  @notroj What do you think?

**Comment by uhliarik** [comment]
Change looks sane.

**Comment by hhorak** [comment]
Cool, thanks, merging.

**Pull request merged**
