### PR TITLE
Support building testing rhel9

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds support for building, testing httpd-container on RHEL9 host.
It updates also README.md with references to `quay.io` registry.
The container-common-scripts are also updated.

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Diff between `2.4/Dockerfile.rhel8` and `2.4/Dockerfile.rhel9`:

```
$ diff 2.4/Dockerfile.rhel8 2.4/Dockerfile.rhel9
1c1
< FROM ubi8/s2i-core:1
---
> FROM ubi9/s2i-core:1
26c26
<       name="rhel8/httpd-24" \
---
>       name="rhel9/httpd-24" \
30c30
<       usage="s2i build https://github.com/sclorg/httpd-container.git --context-dir=examples/sample-test-app/ rhel8/httpd-24 sample-server" \
---
>       usage="s2i build https://github.com/sclorg/httpd-container.git --context-dir=examples/sample-test-app/ rhel9/httpd-24 sample-server" \
36,37c36
< RUN yum -y module enable httpd:$HTTPD_VERSION && \
<     INSTALL_PKGS="gettext hostname nss_wrapper bind-utils httpd mod_ssl mod_ldap mod_session mod_security mod_auth_mellon sscg" && \
---
> RUN INSTALL_PKGS="gettext hostname nss_wrapper bind-utils httpd mod_ssl mod_ldap mod_session mod_security mod_auth_mellon sscg" && \
```

**Comment by phracek** [comment]
Diff between 2.4/Dockerfile.c9s and 2.4/Dockerfile.rhel9:

```bash
$ diff 2.4/Dockerfile.c9s 2.4/Dockerfile.rhel9
1c1
< FROM quay.io/sclorg/s2i-core-c9s:c9s
---
> FROM ubi9/s2i-core:1
26c26
<       name="sclorg/httpd-24-c9s" \
---
>       name="rhel9/httpd-24" \
30c30
<       usage="s2i build https://github.com/sclorg/httpd-container.git --context-dir=examples/sample-test-app/ quay.io/sclorg/httpd-24-c9s sample-server" \
---
>       usage="s2i build https://github.com/sclorg/httpd-container.git --context-dir=examples/sample-test-app/ rhel9/httpd-24 sample-server" \
```

Test results are:
```bash
[0m[0;32m[PASS] Running command 'ct_test_app_dockerfile examples/Dockerfile.s2i 'https://github.com/sclorg/httpd-ex.git' 'Welcome to your static httpd application on OpenShift' app-src'[0m
[0m[0;32m[PASS] Running command 'ct_test_app_dockerfile examples/Dockerfile 'https://github.com/sclorg/httpd-ex.git' 'Welcome to your static httpd application on OpenShift' app-src'[0m

===============================================
Test cases results:


Tests for rhel9/httpd-24:1 succeeded.
++ git remote
++ grep test_
+ git checkout -f origin/master
Previous HEAD position was 524469c Update README.md
```

**Comment by hhorak** [comment]
LGTM, thanks!

**Pull request merged**
