### PR TITLE
move test_latest_imagestreams case into openshift tests

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Jenkins was down. Let's try it again.

[test][test-openshift]

**Comment by phracek** [comment]
Jenkins was down. Let's try it again.

[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Lets try once more
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
OpenShift tests failed on 

```bash
Checking if image registry.redhat.io/openshift3/ose-control-plane:v3.11 is available ...
Starting OpenShift using registry.redhat.io/openshift3/ose-control-plane:v3.11 ...
I1209 11:07:54.777797    2098 config.go:40] Running "create-master-config"
I1209 11:07:58.050900    2098 config.go:46] Running "create-node-config"
I1209 11:07:58.964788    2098 flags.go:30] Running "create-kubelet-flags"
I1209 11:07:59.318829    2098 run_kubelet.go:49] Running "start-kubelet"
I1209 11:07:59.484666    2098 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1209 11:08:44.502056    2098 interface.go:26] Installing "kube-proxy" ...
I1209 11:08:44.502791    2098 interface.go:26] Installing "kube-dns" ...
I1209 11:08:44.502799    2098 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1209 11:08:44.502804    2098 interface.go:26] Installing "openshift-apiserver" ...
I1209 11:08:44.502855    2098 apply_template.go:81] Installing "openshift-apiserver"
I1209 11:08:44.503678    2098 apply_template.go:81] Installing "kube-proxy"
I1209 11:08:44.505038    2098 apply_template.go:81] Installing "kube-dns"
I1209 11:08:44.505189    2098 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1209 11:08:55.043844    2098 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
```

**Pull request merged**
