### PR TITLE
[DO NOT MERGE] Generate certificats that are no longer in rpm

### PR DESCRIPTION
**Pull request by hhorak**
This also fixes the BZ for this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1585533

### CODE REVIEW

**Comment by hhorak** [comment]
Dusty actually suggested even a more correct solution -- generate the certs on container startup.. So, please, do not merge this yet, I'll try to look at whether that variant would work.

**Comment by phracek** [comment]
@hhorak Can you please rebase it? It looks like it blocks #90 .

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
We have a subsription let's one more time

[test][test-openshift]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
@hhorak Thanks for fixing the issue with certificates. I have fixed the issue with Fedora's tests. Feel free to merge it as soon as the tests are green, SCLorg or Testing Farm ;) OpenShift tests are caused by pulling this image https://github.com/sclorg/container-common-scripts/blob/master/test-lib-openshift.sh#L1046. It should be renamed to the image used as from CentOS 7 as for RHEL, `registry.access.redhat.com:ubi7/ubi`, right?

[test]

**Comment by phracek** [comment]
@notroj @uhliarik PTAL if it makes sense. Thanks.

**Comment by hhorak** [comment]
> @notroj @uhliarik PTAL if it makes sense. Thanks.

Specifically when the certificates generation should happen -- whether on container startup is a good idea.

**Comment by notroj** [comment]
I don't understand why https://github.com/sclorg/httpd-container/pull/55/commits/a5433e12970a0a7eade8fe58d32d942bedd2eb7b is necessary, don't the s2i assemble scripts already handle generating the self-signed SSL certs when necessary?

**Comment by notroj** [comment]
> > @notroj @uhliarik PTAL if it makes sense. Thanks.
> 
> Specifically when the certificates generation should happen -- whether on container startup is a good idea.

It should definitely happen at container startup - if and only if the user hasn't provided their own cert/key pair.  We should not be embedding certs directly in distributed images as this seems to do.

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
Certificates are already being generated on container startup. Closing this.

**Pull request closed without merging**
