### PR TITLE
prepare CI and quay enablement for 2.4-micro

### PR DESCRIPTION
**Pull request by pkubatrh**
Needed for #138

### CODE REVIEW

**Comment by pkubatrh** [comment]
@phracek @zmiklank PTAL

**Review by zmiklank — COMMENTED** [review]
If we want to test micro images in openshift too, we need to update also the `openshift-tests.yml`. If not then LGTM.

**Comment by pkubatrh** [comment]
Good point. But do we have openshift tests enabled for fedora, c8s and c9s? I have looked at a few repositories randomly, and have not found any mention of them.

**Comment by zmiklank** [comment]
I have just checked and indeed there are not enabled for Fedora, c8s, c9s.

**Review by phracek — APPROVED** [review]

**Comment by zmiklank** [comment]
Hi @pkubatrh, httpd micro is failing for some reason to build in the build-and-push action:
https://github.com/sclorg/httpd-container/actions/runs/3325894002

**Pull request merged**
