### PR TITLE
[fedora] Don't install yum-utils and update to F34

### PR DESCRIPTION
**Pull request by jpopelka**
Hi,

I needed an F30 based httpd image and since there's no such in registry.fedoraproject.org I had to [build it](https://cloud.docker.com/u/usercont/repository/docker/usercont/httpd).
While doing that I realized there are lots of python 2 dependencies installed and the cause turned out to be `yum-utils`. It's not used during the build process, so I guess it's been there from some historical reasons and it's not needed anymore?

### CODE REVIEW

**Comment by phracek** [comment]
s2i-core base image already exists in Fedora registry (https://registry.fedoraproject.org/repo/f30/s2i-core/tags/). I did not find any reason to having in Fedora `httpd-container` yum-utils package.
So LGTM.

**Comment by phracek** [comment]
[test]

**Comment by pkubatrh** [comment]
[test]

**Comment by mavit** [comment]
Is anything in particular holding this up?  I think we should have Fedora 32 by now, and maybe even be getting ready for Fedora 33.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Test failed on Fedora:

```bash
Step 7/8 : RUN /usr/libexec/s2i/assemble
 ---> Running in db219acf6920

[91m[0m---> Enabling s2i support in httpd24 image
The command '/bin/sh -c /usr/libexec/s2i/assemble' returned a non-zero code: 1
[0m[0;31m[FAIL] Testing 's2i build' with self-signed cert[0m
Resources info:
```

I will investigate it a bit more.

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
Closing this pull request in favor of https://github.com/sclorg/httpd-container/pull/147.

We have automation that regularly pushes the httpd-container image to `quay.io/fedora/httpd-24`.
See tags here: https://quay.io/repository/fedora/httpd-24?tab=tags
The image is based on `s2i-core:35` which is based on Fedora:35 https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.fedora#L2.

**Pull request closed without merging**
