### PR TITLE
tests: set TESTCASE_RESULT to 1 if test fails, not TESTSUITE_RESULT

### PR DESCRIPTION
**Pull request by zmiklank**
Related: https://github.com/sclorg/container-common-scripts/issues/330

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
CentOS 7 Testing Farm should be fixed now.

[test]

**Comment by phracek** [comment]
It looks like on `CentOS Stream 9 - 2.4-micro` is RPM problem.
```bash
Running transaction test
RPM: error: Unable to change root directory: Operation not permitted
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  Errors occurred during test transaction.

Error: building at STEP "RUN MICRO_PKGS="coreutils-single glibc-minimal-langpack" &&     INSTALL_PKGS="$MICRO_PKGS httpd-core mod_ssl findutils hostname nss_wrapper-libs redhat-logos-httpd" &&     dnf install --installroot /mnt/rootfs $INSTALL_PKGS --releasever 9 --setopt install_weak_deps=false --nodocs -y &&     dnf -y --installroot /mnt/rootfs clean all &&     rm -rf /mnt/rootfs/var/cache/* /mnt/rootfs/var/log/dnf* /mnt/rootfs/var/log/yum.*": while running runtime: exit status 1

```

**Comment by zmiklank** [comment]
[test]

**Comment by hhorak** [comment]
The change seems to make the job, but shouldn't we rather use `ct_check_testcase_result` instead of `update_overall` and remove `update_overall()` function entirely? It seems to do exactly the same thing..

**Review by hhorak — CHANGES_REQUESTED** [review]
No approving so far, per previous comment about replacing `update_overall` with `ct_check_testcase_result` instead.

**Comment by zmiklank** [comment]
[test]

**Review by hhorak — APPROVED** [review]
code changes now lgtm, let's see what tests say

**Pull request merged**
