### PR TITLE
Add mod_ldap, mod_session to the package list and make it consistent

### PR DESCRIPTION
**Pull request by notroj**
across all Dockerfiles.  (issue #108)

### CODE REVIEW

**Comment by notroj** [comment]
[test][test-openshift-4]

**Comment by sakthiraam** [comment]
Thank You for adding the support!. Will wait for the merge to happen and available in the RedHat Catalogue.

Regards
Sakthi

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
RHEL7 is caused by a problem with starting OpenShift 3. It looks like docker hub rate limit is involved.
CentOS7 test failed here https://github.com/sclorg/httpd-container/blob/master/test/run-openshift-local-cluster#L42.

**Comment by notroj** [comment]
@phracek Is this safe to merge then, or not?

**Pull request merged**
